# Generated by Django 5.0.6 on 2026-06-19 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageBackground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_key', models.CharField(help_text='home | services | portfolio | about | contact ...', max_length=60, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('bg_type', models.CharField(choices=[('image', 'Static Image'), ('animated', 'Animated Image'), ('video', 'Background Video'), ('gradient', 'Gradient'), ('parallax', 'Parallax'), ('default', 'Default Theme')], default='default', max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('gradient_css', models.CharField(blank=True, max_length=300)),
                ('overlay_opacity', models.FloatField(default=0.4)),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished = preview only')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeoSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('path', models.CharField(help_text='e.g. /, /services', max_length=200, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=400)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.CharField(blank=True, max_length=500)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=40)),
                ('robots', models.CharField(default='index,follow', max_length=60)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Prime Tech', max_length=200)),
                ('tagline', models.CharField(default='Your Security, Our Priority', max_length=200)),
                ('logo', models.CharField(blank=True, max_length=500)),
                ('favicon', models.CharField(blank=True, max_length=500)),
                ('footer_text', models.CharField(default='© Prime Tech. All Rights Reserved.', max_length=300)),
                ('company_desc', models.TextField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('map_embed', models.URLField(blank=True, max_length=600)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#00aaff', max_length=20)),
                ('secondary_color', models.CharField(default='#7b2ff7', max_length=20)),
                ('accent_color', models.CharField(default='#00ffc8', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
    ]
