# Generated by Django 5.0.6 on 2026-06-19 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('before_image', models.CharField(blank=True, max_length=500)),
                ('after_image', models.CharField(blank=True, max_length=500)),
                ('background_image', models.CharField(blank=True, max_length=500)),
                ('background_video', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-completion_date', '-created_at'],
                'abstract': False,
            },
        ),
    ]
