# Generated by Django 5.0.6 on 2026-06-19 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('product', 'Product')], default='product', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('banner_image', models.CharField(blank=True, max_length=500)),
                ('background_image', models.CharField(blank=True, max_length=500)),
                ('background_video', models.CharField(blank=True, max_length=500)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('avatar', models.CharField(blank=True, max_length=500)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('video', 'Video')], default='text', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('video', models.CharField(blank=True, max_length=500)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_label', models.CharField(blank=True, max_length=60)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('specs', models.JSONField(blank=True, default=list)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('video', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out', 'Out of Stock'), ('order', 'On Order')], default='in_stock', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('short_desc', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('banner_image', models.CharField(blank=True, max_length=500)),
                ('background_image', models.CharField(blank=True, max_length=500)),
                ('background_video', models.CharField(blank=True, max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
    ]
